"""Add recent mistakes table

Revision ID: 88493b80354b
Revises: 7504dba056a4
Create Date: 2024-12-29 13:59:46.798187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88493b80354b'
down_revision: Union[str, None] = '7504dba056a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recent_mistakes',
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('mistake_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['test_cards.card_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recent_mistakes')
    # ### end Alembic commands ###
