"""Add position to source link table

Revision ID: cba6f81e6f93
Revises: 88493b80354b
Create Date: 2025-02-01 15:15:40.319182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cba6f81e6f93"
down_revision: Union[str, None] = "88493b80354b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "card_source_link", sa.Column("position", sa.Integer(), nullable=True)
    )
    with op.batch_alter_table("card_source_link", schema=None) as batch_op:
        batch_op.execute("UPDATE card_source_link SET position = ROWID")
        batch_op.alter_column("position", nullable=False)
        batch_op.create_index(
            "idx_position_source",
            ["position", "source_id"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_position_source", table_name="card_source_link")
    op.drop_column("card_source_link", "position")
    # ### end Alembic commands ###
